version: '3.8'

# Development and testing overrides
# This file is automatically loaded by docker-compose when present

services:
  postgres:
    environment:
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements", "-c", "max_connections=100", "-c", "shared_buffers=256MB", "-c", "effective_cache_size=1GB"]
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

  n8n:
    environment:
      - N8N_DIAGNOSTICS_ENABLED=true
      - N8N_LOG_LEVEL=info
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  qdrant:
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

  crawl4ai:
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.1'

  ollama:
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.25'
    # Remove GPU support for development
    devices: []

  ollama-init:
    environment:
      - OLLAMA_HOST=0.0.0.0
    entrypoint:
      - "/bin/sh"
      - "-c"
      - |
        /bin/ollama serve &
        sleep 10
        echo "Development mode: Skipping model downloads"
        echo "Model initialization complete" 